# Generated by Django 2.2.5 on 2020-10-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_status',
            field=models.IntegerField(default=2),
        ),
    ]
