# Generated by Django 2.2.5 on 2020-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_status',
            field=models.IntegerField(default=0),
        ),
    ]
