# Generated by Django 2.2.5 on 2020-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_problem_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='labels',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
